# Generated by Django 4.2.6 on 2023-10-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='/static/images/product_image_1.png', upload_to='products/'),
        ),
    ]
